# -*- coding: utf-8 -*-
"""Copy of week10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13GJgiWuVdsMDw5_aD8fYbKvVeeWYWui6

#Potato Leaf Disease Detection using Image Classification

**Project Description**

 This project focuses on building an image classification model to detect and classify potato plant
diseases. The dataset consists of high-resolution images of potato leaves categorized into three
classes: Early Blight, Late Blight, and Healthy leaves. The goal is to develop a robust deep
learning model that can accurately identify plant diseases and support agricultural diagnostics.

**Objectives**

* Understand image classification using deep learning

* Perform data preprocessing and augmentation

* Train and evaluate a CNN-based model

**Install & Import**
"""

import tensorflow as tf
import numpy as np
import os

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix, classification_report

"""**Download Dataset**"""

import kagglehub

path = kagglehub.dataset_download("hafiznouman786/potato-plant-diseases-data")

print("Dataset path:", path)

"""**Set Correct Dataset Path**"""

dataset_path = os.path.join(path, "PotatoPlants")

"""**Data Preprocessing**"""

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2
)

"""**Load Data**"""

train_data = train_datagen.flow_from_directory(
    dataset_path,
    target_size=(150,150),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_data = train_datagen.flow_from_directory(
    dataset_path,
    target_size=(150,150),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

"""**Check Classes**"""

print(train_data.class_indices)

"""**Build CNN Model**"""

model = Sequential()

model.add(Conv2D(32, (3,3), activation='relu', input_shape=(150,150,3)))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(128, (3,3), activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Flatten())

model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))

# IMPORTANT: dynamic classes
model.add(Dense(train_data.num_classes, activation='softmax'))

"""**Compile Model**"""

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

"""**Train Model**"""

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

"""**Evaluate Model**"""

loss, accuracy = model.evaluate(val_data)
print("Validation Accuracy:", accuracy)

model.save("potato_model.h5")

"""**Confusion Matrix**"""

y_pred = model.predict(val_data)
y_pred_classes = np.argmax(y_pred, axis=1)

y_true = val_data.classes

cm = confusion_matrix(y_true, y_pred_classes)
print("Confusion Matrix:\n", cm)

"""**Classification Report**"""

print(classification_report(y_true, y_pred_classes))

"""**Accuracy Graph**"""

plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.legend()
plt.title("Accuracy Graph")
plt.show()

